**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/creating-reading-and-writing).**

---

In [1]:
import sys

In [2]:
sys.version

'3.7.9 | packaged by conda-forge | (default, Feb 13 2021, 20:03:11) \n[GCC 9.3.0]'

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

Run the code cell below to load libraries you will need (including code to check your answers).

In [2]:
import pandas as pd
pd.set_option('max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

# Exercises

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [5]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = pd.DataFrame([[30,21]], columns=['Apples', 'Bananas'])

# Check your answer
q1.check()
fruits

Correct

   Apples  Bananas
0      30       21

In [ ]:
#q1.hint()
#q1.solution()

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [4]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame([[35, 21], [41,34]], columns=['Apples','Bananas'],
                           index=['2017 Sales','2018 Sales'])

# Check your answer
q2.check()
fruit_sales

Correct

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [5]:
fruit_sales['Apples'][0]

35

In [6]:
fruit_sales['Bananas'][1]

34

In [ ]:
#q2.hint()
#q2.solution()

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [10]:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'], 
                        index=['Flour','Milk','Eggs','Spam'],
                       name = 'Dinner')

# Check your answer
q3.check()
ingredients

Correct

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
#q3.hint()
#q3.solution()

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://i.imgur.com/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [18]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data-130k-v2.csv')
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [22]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv', 
                      index_col=0) # index_col=0을 통해 인덱스를 생략.

# Check your answer
q4.check()
reviews

Correct

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [21]:
#q4.hint()
#q4.solution()

In [26]:
!pwd

/kaggle/working

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [23]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [27]:
animals.Cows # animals['Cows']

Year 1    12
Year 2    20
Name: Cows, dtype: int64

In [29]:
animals.Goats[1]

19

In [33]:
animals[:1]

        Cows  Goats
Year 1    12     22

In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [25]:
# Your code goes here
animals.to_csv('cows_and_goats.csv')

# Check your answer
q5.check()

Correct

In [53]:
pd1 = pd.read_csv('cows_and_goats.csv', index_col=0)
pd1

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [24]:
#q5.hint()
#q5.solution()

Solution:
```python
animals.to_csv("cows_and_goats.csv")
```

# Keep going

Move on to learn about **[indexing, selecting and assigning](https://www.kaggle.com/residentmario/indexing-selecting-assigning)**.

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/161299) to chat with other Learners.*